### ISSUE TITLE
9-stage model picture is unclear

### ISSUE THREAD

**Issue by LourensVeen** [nlesc-sigs/soft-skills#11]
I don't understand the 9-stage picture very well, and it's not explained either. What's this sandwich, and does "hardening" mean the bread is getting stale? How is that an analogy for a conflict? What's wrong with a debate? Are the latter stages about physical violence? Is this win-win/win-lose/lose-lose about actual outcomes or potential outcomes or necessary outcomes?

I found the Wikipedia page to be more intuitive, including the few-word summaries of the stages in this diagram: https://en.wikipedia.org/wiki/Friedrich_Glasl%27s_model_of_conflict_escalation#/media/File:Glasl's_Model_of_Conflict_Escalation.svg

Maybe just removing the rest (or using the diagram from Wikipedia) would simplify things and work just as well?

**Comment by lopeztarifa** [comment]
Great feedback @LourensVeen, thanks. 

There is no doubt this picture and the text need a revision. 

> Maybe just removing the rest (or using the diagram from Wikipedia) would simplify things and work just as well?

Indeed, it is a good suggestion.

**Comment by JensWehner** [comment]
did exactly that.
